// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var React       = require("react");
var ColorData   = require("./colorData.js");
var ColorItem   = require("./colorItem.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statefulComponent("App");

var dummyColors = /* array */[ColorData.parseColorJson(JSON.parse("\n      {\n        \"name\": \"blue\",\n        \"hexcode\": \"#00FFFF\"\n      }\n    "))];

function make(_, _$1) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var match = param[/* state */3][/* colors */0];
      var renderColors = match ? $$Array.map((function (color) {
                return ReasonReact.element(/* Some */[color[/* hexcode */1]], /* None */0, ColorItem.make(color, /* array */[]));
              }), match[0]) : "Loading";
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("div", {
                      className: "App-header"
                    }, React.createElement("h1", undefined, "Iris Colors")), renderColors);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* colors : Some */[dummyColors]];
    });
  return newrecord;
}

exports.component   = component;
exports.dummyColors = dummyColors;
exports.make        = make;
/* component Not a pure module */
