// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/lib/js/src/json_decode.js");

function parseColorJson(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* hexcode */Json_decode.field("hexcode", Json_decode.string, json)
        ];
}

exports.parseColorJson = parseColorJson;
/* No side effect */
