// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("ColorItem");

function make(color, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "color-item"
                }, React.createElement("div", {
                      className: "color-item__preview",
                      style: {
                        backgroundColor: color[/* hexcode */1],
                        height: "50px",
                        width: "100px"
                      }
                    }), React.createElement("div", {
                      className: "color-item__hexcode"
                    }, color[/* hexcode */1]), React.createElement("h2", undefined, color[/* name */0]));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
